# @package _group_
name: Mnih
desc: "https://arxiv.org/pdf/1312.5602v1.pdf"
input_size: null
output_size: null  # set at run time from env
hidden_size: 256
convs:
  - kernel_size: 8
    num_kernels: 16
    stride: 4
  - kernel_size: 4
    num_kernels: 32
    stride: 2
device: cuda