hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
defaults:
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog
  - env: ???
  - model: mnih
agent:
  epsilon:
    start: 1.0
    stop: 0.1
    steps: 250000
    eval: 0.05
  gamma: 0.99
trainer:
  optimizer: adam
  lr: 0.0001
  batch_size: 32
  loss: huber
  baby_step: 4  # fit one batch every 4 actions
  target_step: 10000  # update the target network every 1024 actions
  replay_buffer: 1000000  # max buffer size
  min_replay_buffer_size: 50000  # wait to train until buffer reaches this size
  num_episodes: 20000
  training_time_limit: 86400  # training time limit in seconds
  episode_time_limit: 18000  # max number of actions per episode
  eval_every: 1000
  eval_episodes: 1
settings:
  render_every: 0
  tags: null