hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
defaults:
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog
  - env: ???
  - model: mnih
agent:
  num_episodes: 1000
  epsilon: 0.9
  epsilon_decay: 0.99975
  gamma: 0.99
  lr: 0.00025
  batch_size: 128
  lookback: 3  # stack n + 1 images as input to model
  baby_step: 4  # fit one batch every 4 actions
  target_step: 1024  # update the target network every 1024 actions
  replay_buffer: 50000
settings:
  render: true
  tags: null
  render_every: 1