defaults:
  - env: ???
model:
  hidden_size: 128
  input_size: null
  output_size: null  # set at run time from env
  device: cpu
agent:
  num_episodes: 1000
  epsilon: 0.6
  epsilon_decay: 0.995
  gamma: 0.9
  lr: 0.001
settings:
  render: true
  tags: null